### ISSUE TITLE
Only works on v0.8.x?

### ISSUE THREAD

**Issue by Dovaa** [mafintosh/peercast#4]
i try to install it on Windows 8.1 x64, but i got so many errors :(

```
 Microsoft Windows [Versión 6.3.9600]
(c) 2013 Microsoft Corporation. Todos los derechos reservados.

C:\Users\Dovaa>npm install -g peercast
npm http GET https://registry.npmjs.org/peercast
npm http 304 https://registry.npmjs.org/peercast
npm http GET https://registry.npmjs.org/castv2-client/0.0.5
npm http GET https://registry.npmjs.org/network-address/0.0.4
npm http GET https://registry.npmjs.org/mdns
npm http GET https://registry.npmjs.org/prettysize/0.0.3
npm http GET https://registry.npmjs.org/peerflix
npm http GET https://registry.npmjs.org/read-torrent
npm http GET https://registry.npmjs.org/single-line-log
npm http 304 https://registry.npmjs.org/peerflix
npm http 304 https://registry.npmjs.org/read-torrent
npm http 304 https://registry.npmjs.org/single-line-log
npm http 304 https://registry.npmjs.org/prettysize/0.0.3
npm http 304 https://registry.npmjs.org/castv2-client/0.0.5
npm http GET https://registry.npmjs.org/castv2-client/-/castv2-client-0.0.5.tgz
npm http GET https://registry.npmjs.org/prettysize/-/prettysize-0.0.3.tgz
npm http 304 https://registry.npmjs.org/network-address/0.0.4
npm http GET https://registry.npmjs.org/network-address/-/network-address-0.0.4.
tgz
npm http 304 https://registry.npmjs.org/mdns
npm http 200 https://registry.npmjs.org/prettysize/-/prettysize-0.0.3.tgz
npm http 200 https://registry.npmjs.org/network-address/-/network-address-0.0.4.
tgz
npm http 200 https://registry.npmjs.org/castv2-client/-/castv2-client-0.0.5.tgz
npm http GET https://registry.npmjs.org/magnet-uri
npm http GET https://registry.npmjs.org/parse-torrent
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/airplay-js
npm http GET https://registry.npmjs.org/clivas
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/network-address/0.0.5
npm http GET https://registry.npmjs.org/open/0.0.5
npm http GET https://registry.npmjs.org/pump
npm http GET https://registry.npmjs.org/numeral
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/windows-no-runnable
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/torrent-stream
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/castv2
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/parse-torrent
npm http 304 https://registry.npmjs.org/magnet-uri
npm http 304 https://registry.npmjs.org/airplay-js
npm http 304 https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/thirty-two
npm http GET https://registry.npmjs.org/parse-torrent-file
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/clivas
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/network-address/0.0.5
npm http GET https://registry.npmjs.org/network-address/-/network-address-0.0.5.
tgz
npm http 304 https://registry.npmjs.org/pump
npm http 304 https://registry.npmjs.org/numeral
npm http 304 https://registry.npmjs.org/open/0.0.5
npm http GET https://registry.npmjs.org/open/-/open-0.0.5.tgz
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/windows-no-runnable
npm http 304 https://registry.npmjs.org/torrent-stream
npm http 304 https://registry.npmjs.org/castv2
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/protobufjs
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/parse-torrent-file
npm http 304 https://registry.npmjs.org/mime

> mdns@2.2.8 install C:\Users\Dovaa\AppData\Roaming\npm\node_modules\peercast\n
ode_modules\mdns
> node-gyp rebuild


C:\Users\Dovaa\AppData\Roaming\npm\node_modules\peercast\node_modules\mdns>node
 "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild
npm http GET https://registry.npmjs.org/bencode
npm http GET https://registry.npmjs.org/simple-sha1
npm http 304 https://registry.npmjs.org/thirty-two
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform T
oolset = 'v110') cannot be found. To build using the v110 build tools, please i
nstall Visual Studio 2012 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Upgrade Solution...". [C:\Users\Dovaa\AppData\Roami
ng\npm\node_modules\peercast\node_modules\mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dovaa\AppData\Roaming\npm\node_modules\peercast\node_modu
les\mdns
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild mdns@2.2.8
unbuild peercast@1.1.2
npm ERR! weird error 1
npm http 304 https://registry.npmjs.org/form-data
npm http 200 https://registry.npmjs.org/network-address/-/network-address-0.0.5.
tgz
npm http 304 https://registry.npmjs.org/hawk
unbuild peerflix@0.28.0
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 200 https://registry.npmjs.org/open/-/open-0.0.5.tgz
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/forever-agent
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.1
3","npm":"1.3.2"})
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/protobufjs
npm http 304 https://registry.npmjs.org/bencode
npm http 304 https://registry.npmjs.org/simple-sha1
npm http GET https://registry.npmjs.org/bytebuffer
npm http GET https://registry.npmjs.org/ascli
npm http GET https://registry.npmjs.org/rusha
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/bytebuffer
npm http 304 https://registry.npmjs.org/ascli
npm http GET https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz
npm http GET https://registry.npmjs.org/hoek/-/hoek-0.7.6.tgz
npm http GET https://registry.npmjs.org/colour
npm http GET https://registry.npmjs.org/optjs
npm http GET https://registry.npmjs.org/long
npm http GET https://registry.npmjs.org/bufferview
npm http 304 https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/rusha
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 200 https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http 200 https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz
npm http 304 https://registry.npmjs.org/bufferview
npm http 304 https://registry.npmjs.org/long
npm http 304 https://registry.npmjs.org/colour
npm http 200 https://registry.npmjs.org/hoek/-/hoek-0.7.6.tgz
npm http GET https://registry.npmjs.org/colour/-/colour-0.7.1.tgz
npm http 304 https://registry.npmjs.org/optjs
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.13
","npm":"1.3.2"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.
10.13","npm":"1.3.2"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.13
","npm":"1.3.2"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.13
","npm":"1.3.2"})
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tg
z
npm http 304 https://registry.npmjs.org/rusha
unbuild parse-torrent-file@2.1.1
unbuild parse-torrent@4.0.0
unbuild read-torrent@1.3.0
npm http 200 https://registry.npmjs.org/colour/-/colour-0.7.1.tgz
npm http 200 https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tg
z
npm ERR! not ok code 0

C:\Users\Dovaa>
```

i try installing the build tools for Visual Studio 2012 (as I see in the log that ask me for that)
but i got the same problem anyway, is only node 0.8.x or something else? 
can some1 give me a hand? xP

**Comment by Dovaa** [comment]
i got the same error on ubuntu:

```
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.36","npm":"1.4.28"})

> mdns@2.2.8 install /usr/lib/node_modules/peercast/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/dovaa/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/peercast/node_modules/mdns/.node-gyp"
make: se ingresa al directorio «/usr/lib/node_modules/peercast/node_modules/mdns/build»
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No existe el archivo o el directorio
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: se sale del directorio «/usr/lib/node_modules/peercast/node_modules/mdns/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/peercast/node_modules/mdns
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm ERR! mdns@2.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.8 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-31-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "peercast"
npm ERR! cwd /home/dovaa
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

so only works on v0.8.x or is node-gyp rebuild?

**Comment by maantje** [comment]
I had te same issue i managed to fix it with the following steps

1) Install nw-gyp by running: npm install -g nw-gyp
2) Enter in the node_modules/peercast/node_modules/mdns folder of your node-webkit project
3) Run nw-gyp configure --target=0.12.2 (this target is the version of the node-webkit you have installed you can get your version by adding alert(process.versions['node-webkit']) and opening your app)
4) And finally run nw-gyp build

And now it works fine!

**Comment by mafintosh** [comment]
I know @watson is working on a js version of bonjour that will fix this
