### ISSUE TITLE
impossible to install on windows 10 with node 5.0 : compile error

### ISSUE THREAD

**Issue by andreabisello** [mafintosh/peercast#5]
thanks for this awesome tool.
i'm not able to install it on windows 10 with node 5.0 : there is a compile error.

this is the log

C:\Users\Computer>npm install -g peercast
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
C:\Users\Computer\AppData\Roaming\npm\peercast -> C:\Users\Computer\AppData\Roaming\npm\node_modules\peercast\bin.js

> mdns@2.2.10 install C:\Users\Computer\AppData\Roaming\npm\node_modules\peercast\node_modules\mdns
> node-gyp rebuild

C:\Users\Computer\AppData\Roaming\npm\node_modules\peercast\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
MSBUILD : error MSB3428: impossibile caricare il componente di Visual C++ "VCBuild.exe". Per risolvere il problema, 1) installare .NET Frame
work 2.0 SDK, 2) Microsoft Visual Studio 2005 oppure 3) aggiungere al percorso di sistema il percorso del componente se questo è installato
altrove.  [C:\Users\Computer\AppData\Roaming\npm\node_modules\peercast\node_modules\mdns\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Computer\AppData\Roaming\npm\node_modules\peercast\node_modules\mdns
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:mdns mdns@2.2.10 install: `node-gyp rebuild`
npm WARN install:mdns Exit status 1
C:\Users\Computer\AppData\Roaming\npm
└── (empty)

npm ERR! code 1

C:\Users\Computer>

i try to install node-gyp but nothing changed.

so i downloaded and reinstalled net framework sdk 2.0 but nothing changed.

any suggestion?

thanks

**Comment by mafintosh** [comment]
I know @watson is working on a js version of bonjour that should fix this issue
