### ISSUE TITLE
dns service error: unknown

### ISSUE THREAD

**Issue by deyaaeldeen** [mafintosh/peercast#6]
I get the following error:
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
/usr/lib/node_modules/peercast/node_modules/mdns/lib/browser.js:86
  dns_sd.DNSServiceBrowse(self.serviceRef, flags, ifaceIdx, '' + requested_type,
         ^

Error: dns service error: unknown
    at Error (native)
    at new Browser (/usr/lib/node_modules/peercast/node_modules/mdns/lib/browser.js:86:10)
    at Object.create [as createBrowser](/usr/lib/node_modules/peercast/node_modules/mdns/lib/browser.js:114:10)
    at module.exports (/usr/lib/node_modules/peercast/index.js:25:22)
    at /usr/lib/node_modules/peercast/bin.js:19:16
    at /usr/lib/node_modules/peercast/node_modules/read-torrent/index.js:18:13
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)

I am using arch linux with kernel 4.2.5-1

**Comment by deyaaeldeen** [comment]
It looks like I should start avahi service first.
