### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by deyaaeldeen** [mafintosh/peercast#7]
I get this error now after starting avahi and using peercast:

**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Chromecast is connecting
Connected to 0/0 peers
Downloaded 0 Bytes (0 b/s) with 0 hotswaps
Uploaded 0 Bytes (0 b/s)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/usr/lib/node_modules/peercast/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/usr/lib/node_modules/peercast/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/usr/lib/node_modules/peercast/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)

**Comment by mafintosh** [comment]
I know @watson is working on a js version of bonjour/avahi thats gonna fix this

**Comment by watson** [comment]
Yep - been busy the last couple of days :stuck_out_tongue_winking_eye: It's in the oven as we speak :smile:

**Comment by deyaaeldeen** [comment]
Thanks, looking forward for it.
